server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/markbay_test
    username: root
    password: Onadiran1#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  output:
    ansi:
      enabled: always


logging:
  file:
    name: loggers.log
